### ISSUE TITLE
The implementation may be incorrect because the two embedding layers are very sparse.

### ISSUE THREAD

**Issue by BigAndSweet** [twjiang/graphSAGE-pytorch#13]
Recently I am using your pytorch-graphSage, and I am running "python -m src.main --epochs 50  --learn_method unsup" with your default setting in the default dataset. I also removed line73-76 of main.py and run with the above command. 

In both settings, I found that cur_hidden_embs in line 267 of models.py is very sparse, so that the resulted embed feature is also very sparse. Instead, cur_hidden_embs should be dense. I was wondering if something is wrong.

**Comment by zhao-tong** [comment]
I don't get your question. What is the problem of it being sparse? I wouldn't expect the average of 10 sparse vectors to be fully dense.

**Comment by BigAndSweet** [comment]
Hi，thanks for your help. I suppose that cur_hidden_embs should be dense, which is also verified in teh tensorflow version https://github.com/williamleif/GraphSAGE. However, after running with the default setting and dataset I only find that cur_hidden_embs   has too much zero values, and such sparse weight matrix can lose much information when it is used for the embedding operation.

**Comment by zhao-tong** [comment]
hmm, maybe you can compare the final learned embeddings from both models with node classification task to see if they have a performance gap, which should be a better indicator of the learned embeddings' quality.

**Comment by zhao-tong** [comment]
closing as the questioner stopped replying. will re-open if needed in the future.
