### ISSUE TITLE
How to perform the inductive learning?

### ISSUE THREAD

**Issue by Peterecoding** [twjiang/graphSAGE-pytorch#14]
This implementation seems to be transductive learning, which is reflected in Line-279, models.py. Self.adj_lists includes all nodes and edges of the graph. How to conduct the inductive learning? Thank you!

**Comment by zhao-tong** [comment]
Hi, to make it work for inductive learning, you would need to update the data (features and adj_lists) every time before and after you evaluate the model in each epoch.

**Comment by Peterecoding** [comment]
Fine, thanks for your reply! I construct train_adj_list and test_adj_lists. The former only contains train nodes set, while the latter includes all nodes.
