### ISSUE TITLE
typo in line 73 of main.py?

### ISSUE THREAD

**Issue by jaks19** [twjiang/graphSAGE-pytorch#16]
Do you want to check `=='unsup`' to allow classification training as it is now? 

Or should it rather be `!='unsup`'? 

It does not make sense to me that when we specify 'unsup' that classification is still used for training. But I may be missing something?

Thanks

**Comment by zhao-tong** [comment]
No, it's not a typo. The classification model is independent from the main model. We need to train a classification MLP to evaluate the representations.

**Comment by jaks19** [comment]
> No, it's not a typo. The classification model is independent from the main model. We need to train a classification MLP to evaluate the representations.

That makes a lot of sense, thanks for the clarification!
